# Generated by Django 4.1.7 on 2023-06-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cac_2023', '0002_alter_datos_sensores_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor_hidrostatico',
            name='mareografos',
        ),
        migrations.AddField(
            model_name='mareografo',
            name='sensores',
            field=models.ManyToManyField(related_name='sensores', to='cac_2023.sensor_hidrostatico'),
        ),
    ]
