# Generated by Django 4.1.7 on 2023-06-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cac_2023', '0003_remove_sensor_hidrostatico_mareografos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_hidrostatico',
            name='tipo',
            field=models.CharField(max_length=8, verbose_name='Tipo de sensor'),
        ),
    ]
